const fs = require("fs");
const path = require("path");

const OBSIDIAN_VAULT = path.join(__dirname, "..", "obsidian-vault");

function ensureDir(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function formatDate(dateStr) {
  const date = new Date(dateStr);
  const pad = (n) => n.toString().padStart(2, "0");
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())} ${pad(date.getHours())}:${pad(date.getMinutes())}`;
}

function formatTime(sec) {
  if (sec === null || sec === undefined) return "";
  const m = Math.floor(sec / 60);
  const s = Math.floor(sec % 60);
  return m > 0 ? `${m}:${s.toString().padStart(2, "0")}` : `${s}s`;
}

function getLevelColor(level) {
  const colors = {
    A: "#16a34a",
    B: "#22c55e",
    C: "#ca8a04",
    D: "#ea580c",
    E: "#dc2626",
  };
  return colors[level] || "#666";
}

function getEmotionEmoji(label) {
  const map = {
    "平静": "😐",
    "愉悦": "😊",
    "焦急": "😰",
    "愤怒": "😠",
    "不满": "😒",
    "困惑": "🤔",
    "冷漠": "😑",
    "惊讶": "😲",
  };
  return map[label] || "";
}

function generateNoteContent(data) {
  const q = data.quality;
  const dims = q.dimensions;
  const summary = data.callSummary || data.summary;

  const content = `---
aliases:
tags: [质检报告, 客服质检, ${q.level}级]
date: ${formatDate(data.timestamp)}
filename: ${data.fileName}
totalScore: ${q.totalScore}
level: ${q.level}
---

# 📞 ${data.fileName} 质检报告

## 📊 评分概览

| 项目 | 分数 | 等级 |
|------|------|------|
| 综合评分 | **${q.totalScore}** | <span style="color:${getLevelColor(q.level)}">**${q.level}级**</span> |

### 各维度详情

| 维度 | 分数 | 评价 |
|------|------|------|
| 📋 话术合规 | ${dims.compliance.score}/10 | ${dims.compliance.reason} |
| 📚 业务知识 | ${dims.knowledge.score}/10 | ${dims.knowledge.reason} |
| 🔄 流程完整 | ${dims.process.score}/10 | ${dims.process.reason} |
| 💬 沟通技巧 | ${dims.communication.score}/10 | ${dims.communication.reason} |

---

## 🎯 质检结论

**${data.summary?.title || q.level + '级 — ' + q.totalScore + '分'}**

> ${data.summary?.verdict || (q.totalScore >= 80 ? "服务表现良好" : q.totalScore >= 60 ? "服务基本合格" : "服务需改进")}

### 亮点

${(data.summary?.highlights || []).map(h => `- ${h}`).join("\n")}

### 情绪分析

${data.emotion?.overall || "无"}

---

${summary ? `
## 📋 通话总结

### 通话目的
${summary.callPurpose || "未知"}

### 客户主要诉求
${summary.customerRequest || "无"}

### 关键要点
${(summary.keyPoints || []).map(p => `- ${p}`).join("\n")}

### 解决状态
${summary.resolutionStatus || "未知"}

### 后续行动项
${(summary.actionItems || []).map(a => `- ${a}`).join("\n")}

### 质量问题
${(summary.qualityIssues || []).map(i => `- ${i}`).join("\n")}

### 总体评价
${summary.overallAssessment || "无"}

### 改进建议
${(summary.improvementSuggestions || []).map(s => `- ${s}`).join("\n")}

---

` : ''}
## 📝 对话转写

${data.utterances.map((u, i) => {
  const role = u.role === "agent" ? "客服" : "客户";
  const roleEmoji = u.role === "agent" ? "👤" : "👥";
  const emotion = u.emotion?.label ? getEmotionEmoji(u.emotion.label) + " " + u.emotion.label : "";
  return `### ${i + 1}. ${roleEmoji} ${role} [${formatTime(u.start)} ~ ${formatTime(u.end)}] ${emotion}

> ${u.text}`;
}).join("\n\n")}

---

## ⚠️ 违规记录

${q.violations && q.violations.length > 0 
  ? q.violations.map(v => `- **${v.severity === "critical" ? "严重" : v.severity === "major" ? "一般" : "轻微"}**: ${v.detail}`).join("\n")
  : "✅ 未检出违规项"}

---

## 💡 改进建议

${q.suggestions.map((s, i) => `${i + 1}. ${s}`).join("\n")}

---

*Generated by 录音质检系统 | ${formatDate(new Date().toISOString())}*
`;

  return content;
}

async function exportToObsidian(data) {
  const vaultPath = OBSIDIAN_VAULT;
  const reportsDir = path.join(vaultPath, "质检报告");
  const attachmentsDir = path.join(reportsDir, "附件");
  
  ensureDir(reportsDir);
  ensureDir(attachmentsDir);

  const baseName = String(data.fileName || "质检报告").replace(/\.[^.\\/]+$/, "");
  const safeName = baseName.replace(/[\\/:*?"<>|\r\n]+/g, "_").trim() || "质检报告";
  const timestamp = new Date().toISOString().replace(/[-:.T]/g, "").slice(0, 14);
  const fileName = `${timestamp}_${safeName}.md`;
  const filePath = path.join(reportsDir, fileName);

  const content = generateNoteContent(data);
  fs.writeFileSync(filePath, content, "utf-8");

  const jsonContent = JSON.stringify(data, null, 2);
  const jsonFileName = `${timestamp}_${safeName}_原始数据.json`;
  fs.writeFileSync(path.join(attachmentsDir, jsonFileName), jsonContent, "utf-8");

  return {
    success: true,
    filePath,
    fileName,
    vaultPath,
  };
}

function getVaultStats() {
  const vaultPath = OBSIDIAN_VAULT;
  const reportsDir = path.join(vaultPath, "质检报告");
  
  if (!fs.existsSync(reportsDir)) {
    return { totalReports: 0, vaultExists: false };
  }

  const files = fs.readdirSync(reportsDir).filter(f => f.endsWith(".md"));
  return {
    totalReports: files.length,
    vaultExists: true,
    vaultPath,
  };
}

module.exports = { exportToObsidian, getVaultStats };
